src/flask_app/flask_login_tutorial/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for, current_app
from flask_login import current_user, login_user
from . import login_manager
from .forms import LoginForm, SignupForm
from .models import User, db
import time    
from datetime import datetime, date, time, timezone, timedelta
import pytz


auth_bp = Blueprint(
    "auth_bp", __name__, url_prefix="/"
)


def mysql_time() -> str:
    unaware_utc = datetime.now(timezone.utc)
    current_app.logger.debug('tz: Timezone naive:', unaware_utc)

    then = unaware_utc + timedelta(hours=1)

    aware = datetime.now(pytz.utc)
    current_app.logger.debug('tz: Timezone Aware:', aware)

    # US/Central timezone datetime
    aware_europe_berlin = datetime.now(pytz.timezone('Europe/Berlin'))
    current_app.logger.debug('tz: Europe/Berlin DateTime', aware_europe_berlin)

    return aware_europe_berlin.strftime('%Y-%m-%d %H:%M:%S')


@auth_bp.route("/signup", methods=["GET", "POST"])
def signup():
    """
    User sign-up page.

    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            user = User(
                name=form.name.data, email=form.email.data, website=form.website.data, created_on=mysql_time()
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()  # Create new user

            current_app.logger.debug("LOGIN detected: "+user.email)

            login_user(user)  # Log in as newly created user
            return redirect(url_for("main_bp.dashboard"))
        flash("A user already exists with that email address.")
    return render_template(
        "signup.jinja2",
        title="Create an Account.",
        form=form,
        template="signup-page",
        body="Sign up for a user account.",
    )


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    current_app.logger.debug("CONN: "+str(request.headers.get('X-Real-Ip')))
    """
    Log-in page for registered users.

    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """
    # Bypass if user is logged in
    if current_user.is_authenticated:
        current_app.logger.debug("LOGIN detected: "+current_user.email)            
        return redirect(url_for("main_bp.dashboard"))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):

            print("UPDATE USER LOGIN TIME")
            user.update_last_login()
            
            login_user(user)
            next_page = request.args.get("next")
            return redirect(next_page or url_for("main_bp.dashboard"))
        flash("Invalid username/password combination")
        return redirect(url_for("auth_bp.login"))
    return render_template(
        "login.jinja2",
        form=form,
        title="Log in.",
        template="login-page",
        body="Log in with your User account.",
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash("You must be logged in to view that page.")
    return redirect(url_for("auth_bp.login"))

src/flask_app/flask_login_tutorial/routes.py
"""Logged-in page routes."""
from flask import Blueprint, redirect, render_template, url_for, request
from flask_login import current_user, login_required, logout_user

main_bp = Blueprint(
    "main_bp", __name__, template_folder="templates", static_folder="static", url_prefix="/"
)


@main_bp.route("/", methods=["GET"])
@login_required
def dashboard():
    """Logged-in User Dashboard."""
    return render_template(
        "dashboard.jinja2",
        title="Flask-Login Tutorial",
        template="dashboard-template",
        current_user=current_user,
        body="You are now logged in!",
    )


@main_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for("auth_bp.login"))

src/flask_app/flask_login_tutorial/routes/invoices.py
from flask import Blueprint, render_template, render_template_string, redirect, url_for, request
from pprint import pprint
import requests
import extruct
from w3lib.html import get_base_url
import time
import uuid
import os
import json
from urllib.parse import urlparse
from bs4 import BeautifulSoup
import lxml.html as lh
import lxml
from flask_login import current_user, login_required, logout_user, login_user
from flask_httpauth import HTTPBasicAuth
from base64 import b64decode
from flask_login_tutorial.models import User
from flask_login_tutorial.decorators import login_required_ext
invoices_bp = Blueprint(
    "invoices_bp", __name__, url_prefix="/invoices", template_folder="templates", static_folder="static"
)


@login_required_ext
@invoices_bp.route("/", methods=['GET', 'POST'])
def invoices_index():
    return render_template("invoices.jinja2",
                           template="dashboard-template",
                           body="Invoices Index")

@login_required_ext
@invoices_bp.route("/create", methods=['GET', 'POST'])
def invoices_create_index():
    if request.method == "GET":
        return render_template("invoices_create.jinja2",
                           template="dashboard-template",
                           body="Invoices CREATE")
    else:
        return render_template("invoices_create-show.jinja2",
                           template="dashboard-template",
                           body="Invoices CREATE")

src/flask_app/flask_login_tutorial/routes/main.py
"""Logged-in page routes."""
from flask import Blueprint, redirect, render_template, url_for, request, session, abort, jsonify
from flask_login import current_user, login_required, logout_user
from flask_login_tutorial.models import User
main_bp = Blueprint(
    "main_bp", __name__, template_folder="templates", static_folder="static", url_prefix="/"
)
from io import BytesIO
import pyqrcode

@main_bp.route("/", methods=["GET"])
@login_required
def dashboard():
    """Logged-in User Dashboard."""
    return render_template(
        "dashboard.jinja2",
        title="Flask-Login Tutorial",
        template="dashboard-template",
        current_user=current_user,
        body="You are now logged in!",
    )


@main_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for("auth_bp.login"))

@main_bp.route('/qrcode')
def qrcode():
    if not current_user.is_authenticated:
        abort(404)
    user = User.query.filter_by(username=current_user.username).first()
    print(user.get_totp_uri())
    url = pyqrcode.create(user.get_totp_uri())
    stream = BytesIO()
    url.svg(stream, scale=5)
    xml_data = stream.getvalue()
    return xml_data, 200, {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'}


@main_bp.route('/set_2fa_enabled', methods=["GET", "POST"])
def set_2fa_enabled():
    if not current_user.is_authenticated:
        abort(404)
    user = User.query.filter_by(username=current_user.username).first()
    print(request.values.get("new_state"))
    print(dict(request.values).keys())
    state_ = request.values.get("new_state")
    
    user.set_two_factor(state_)
    return jsonify({"success": user.twofactor_enabled == state_})
    

src/flask_app/flask_login_tutorial/routes/oauth.py
from flask import Blueprint, render_template, render_template_string, redirect, url_for, request, current_app, jsonify
from pprint import pprint
import requests
import extruct
from w3lib.html import get_base_url
import time
import uuid
import os
import json
from urllib.parse import urlparse
from bs4 import BeautifulSoup
import lxml.html as lh
import lxml
from flask_login import current_user, login_required, logout_user
from flask_login_tutorial.models import OAuth2Client, db, create_bearer_token_validator, OAuth2Token
from werkzeug.security import gen_salt
from authlib.integrations.flask_oauth2 import current_token


from authlib.integrations.flask_oauth2 import (
    AuthorizationServer,
    ResourceProtector,
)


require_oauth = ResourceProtector()
bearer_cls = create_bearer_token_validator(db.session, OAuth2Token)
require_oauth.register_token_validator(bearer_cls())

oauth_bp = Blueprint(
    "oauth_bp", __name__, url_prefix="/oauth", template_folder="templates", static_folder="static"
)



def split_by_crlf(s):
    return [v for v in s.splitlines() if v]


@oauth_bp.route('/authorize', methods=['GET', 'POST'])
def oauth_authorize():
    authorization = current_app.config['auth']
    user = current_user
    # if user log status is not true (Auth server), then to log it in
    if not user:
        return redirect(url_for('oauth_bp.oauth_index', next=request.url))
    if request.method == 'GET':
        try:
            grant = authorization.get_consent_grant(end_user=user)
        except OAuth2Error as error:
            return error.error
        return render_template("oauth2_authorize.jinja2",
                           template="dashboard-template",
                           body="OAuth Index", user=user, grant=grant)
    if not user and 'username' in request.form:
        username = request.form.get('username')
        user = User.query.filter_by(name=username).first()
    if request.form['confirm']:
        grant_user = user
    else:
        grant_user = None
    return authorization.create_authorization_response(grant_user=grant_user)



@login_required
@oauth_bp.route("/", methods=['GET', 'POST'])
def oauth_index():
    if request.method == 'POST':
        username = request.form.get('username')
        user = User.query.filter_by(name=username).first()
        if not user:
            user = User(name=username)
            db.session.add(user)
            db.session.commit()
        session['id'] = user.id
        # if user is not just to log in, but need to head back to the auth page, then go for it
        next_page = request.args.get('next')
        if next_page:
            return redirect(next_page)
        return redirect('/')
    else:
        if current_user.is_authenticated:
            clients = OAuth2Client.query.filter_by(user_id=current_user.id).all()
        else:
            return redirect(url_for("auth_bp.login"))
        json_ = "{}"
        return render_template("oauth.jinja2",
                               template="dashboard",
                               body="OAuth Index",
                               user=current_user, clients=clients
                               )

@oauth_bp.route("/create_client", methods=['GET', 'POST'])
def oauth_create_client():
    if current_user.is_authenticated:
        clients = OAuth2Client.query.filter_by(user_id=current_user.id).all()
        print(clients)
    if request.method == "GET":
        return render_template("oauth2_create_client.jinja2", template="dashboard-template",
        body="CREATE CLIENT")
       
    client_id = gen_salt(24)
    client_id_issued_at = int(time.time())
    client = OAuth2Client(
        client_id=client_id,
        client_id_issued_at=client_id_issued_at,
        user_id=current_user.id,
    )
    form = request.form
    
    client_metadata = {
        "client_name": form["client_name"],
        "client_uri": form["client_uri"],
        "grant_types": split_by_crlf(form["grant_type"]),
        "redirect_uris": split_by_crlf(form["redirect_uri"]),
        "response_types": split_by_crlf(form["response_type"]),
        "scope": form["scope"],
        "token_endpoint_auth_method": form["token_endpoint_auth_method"]
    }
    client.set_client_metadata(client_metadata)
    
    
    
    if form['token_endpoint_auth_method'] == 'none':
        client.client_secret = ''
    else:
        client.client_secret = gen_salt(48)
    
    db.session.add(client)
    db.session.commit()
    return redirect(url_for("oauth_bp.oauth_index"))

@oauth_bp.route('/token', methods=['POST'])
def issue_token():
    authorization = current_app.config['auth']
    
    resp = authorization.create_token_response()
    return resp

@oauth_bp.route('/revoke', methods=['POST'])
def revoke_token():
    authorization = current_app.config['auth']
    return authorization.create_endpoint_response('revocation')

src/flask_app/flask_login_tutorial/templates/2fa-login.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}
{% block content %}

<h1>2FA-Authentication Enabled</h1>
<h4>Please enter token from Authentication App</h4>
<form action="" method="post">
<input type="hidden" name="login_method" value="2fa">
<input type="text" name="email" value="{{ email }}">
<input type="text" maxlength="6" name="token">
<input type="submit" value="Login">
<a href="javascript:history.back()">Go Back</a>

{% endblock %}

src/flask_app/flask_login_tutorial/templates/2fa.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}
{% block content %}
	<style>
		.container {
			height: auto !important;
		}
		div.slideControlContent {
	width: 100%;
	height: 200px;
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
	align-items: center;
	align-content: center;
	padding: 0 40%;
	text-align: center;
}
span.slideControl {
	flex: 1 100%;
	max-width: 40px;
	height: 10px;
	border-radius: 5px;
	background: #fff;
	display: inline-block;
	margin: 8px 8px 0 0;
	position: relative;
	cursor: pointer;
}
span.slideControl::before {
	content: '';
	position: absolute;
	left: 0;
	top: 0;
	width: 100%;
	height: 100%;
	border-radius: 5px;
	background: #d35d5d;
	box-shadow: inset 0 4px 8px 0 rgba(46,43,56,0.16);
	z-index: 1;
}
span.slideControl.active::before {
	background: #5dd39e;
}
span.slideControl::after {
	content: '';
	position: absolute;
	left: 2px;
	top: -7px;
	width: 24px;
	height: 24px;
	background: #3f3f3f;
	box-shadow: 0 4px 8px 0 rgba(46,43,56,0.16), 0 8px 16px 0 rgba(46,43,56,0.08), 0 16px 32px 0 rgba(46,43,56,0.04);
	z-index: 9;
	border-radius: 50%;
	margin: 0;
	-webkit-transition: all 0.3s linear;
	-moz-transition: all 0.3s linear;
	-ms-transition: all 0.3s linear;
	-o-transition: all 0.3s linear;
	transition: all 0.3s linear;
}
span.slideControl.active::after {
	left: 100%;
	margin: 0 0 0 -26px;
}
span.slideControlCheckbox {
	flex: 1 100%;
	padding: 24px 0 12px 0;
}
span.slideControlMessage {
	flex: 1 100%;
}
		
		
		</style>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-12">
      <div class="jumbotron text-center p-4">
        <h2>Two-Factor Authentication Setup</h2>
		
		
	
      </div>
	</div>
  </div>

  <div class="row justify-content-center">
    <div class="col-12">
      
        
          <h5 style="text-align: left;">Instructions!</h5>
		    <div class="container-fluid" style="background: #FFF; border: 1px solid #333; padding: 1rem; color: #111;">
				<div class="row">
					<div class="col-12">
					<img id="qrcode" style="max-width: 100%; height: auto;" src="{{ url_for('main_bp.qrcode') }}">
					</div>
				</div>
				<div class="row">
					<div class="col-12">
					
						<ul style="list-style: none; text-align: center;">
				<li>Download <a style="margin-top: .25rem !important; margin-bottom: .5rem; color: #9d007b;" href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en&gl=US" target="_blank">Google Authenticator</a> on your mobile.</li>
				<li>Create a new account with <strong>setup key</strong> method.</li>
				<li>Provide the required details (name, secret key).</li>
				<li>Select time-based authentication.</li>
				<li>Submit the generated key in the form.</li>
			  </ul>
					
					</div>
				</div>

			</div>
          
		 
        </div>
	<form>
        <div class="form-group">
          <label for="secret">Secret Token</label>
          <input type="text" class="form-control" id="secret" value="{{ secret }}" readonly>
        </div>
        <div class="text-center">
          <button type="button" class="btn btn-primary" onclick="copySecret()">Copy Secret</button>
        </div>
		
		
		<div class="form-group">
          <label for="otp">Generated OTP URL</label>
          <input type="text" class="form-control" id="totp_url" name="otp" value="{{ totp_url }}">
        </div>
		<div class="text-center">
          <button type="button" class="btn btn-primary" onclick="copyOTPURL()">Copy URL</button>
        </div>
		
		
		
      </form>
    </div>
	  <div class="row">
  <div>
		<div class="slideControlContent">
		<label for="twofactor_enabled_cb">
		Enabled?
		</label>
			<span class="slideControl"></span>
			<span class="slideControlCheckbox"><input id="twofactor_enabled_cb" style="display: none;" type="checkbox" {% if twofactor_enabled == 1 %}checked{% endif %}></span>
		</div>
  </div>
  </div>
	<div class="row">
    <div class="col-lg-7">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      <form method="POST">
        <div class="form-group">
          <label for="otp">Generated OTP</label>
          <input type="hidden" name="secret" value="{{ secret }}" required>
          <input type="number" class="form-control" id="otp" name="otp" required>
        </div>
		
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Authenticate User</button>
        </div>
      </form>
    </div>
  </div>
    <div class="row">
  <div class="col-12">

	</div>
	<a href="javascript:history.back()">Go Back</a>
	</div>

</div>

<script>
  function copySecret() {
    /* Get the text field */
    var copyText = document.getElementById("secret");

    /* Select the text field */
    copyText.select();
    copyText.setSelectionRange(0, 99999); /*For mobile devices*/

    /* Copy the text inside the text field */
    document.execCommand("copy");

    alert("Successfully copied TOTP secret token!");
  }
  
  
  function copyOTPURL() {
  /* Get the text field */
    var copyText = document.getElementById("totp_url");

    /* Select the text field */
    copyText.select();
    copyText.setSelectionRange(0, 99999); /*For mobile devices*/

    /* Copy the text inside the text field */
    document.execCommand("copy");
  }
</script>

		<script>

$(document).ready(function() {

		var state	=	jQuery( 'input' ).prop('checked');
		
		if ( state == false ) {
			jQuery('span.slideControl').removeClass('active');
			jQuery( 'input' ).prop('checked', false );
			var status	=	'false';
		} else {
			jQuery('span.slideControl').addClass('active');
			jQuery( 'input' ).prop('checked', true );
			var status	=	'true';
		}

		jQuery( 'span.slideControlMessage' ).html( status );



			
			jQuery('span.slideControl').on('click', function() {
	var old_state = state
		var state	=	jQuery( 'input' ).prop('checked');
		
		if ( state == true ) {
			jQuery( this ).removeClass('active');
			jQuery( 'input' ).prop('checked', false );
			var status	=	'false';
		} else if ( state == false ) {
			jQuery( this ).addClass('active');
			jQuery( 'input' ).prop('checked', true );
			var status	=	'true';
		}
	if(state != old_state) {
		console.log("changed")
		$.ajax({
			url: '/set_2fa_enabled',
			type: 'POST',
			data: {
				new_state: state
			},
			success: function(data) {
				console.log(data)
			}
		// old_state = state
		})
		jQuery( 'span.slideControlMessage' ).html( status );

	}

	})

})


		
		</script>
{% endblock %}

src/flask_app/flask_login_tutorial/templates/analytics.jinja2
<script type="text/javascript">
  
</script>

src/flask_app/flask_login_tutorial/templates/dashboard.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
  <h1>{{ body }}</h1>

  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('main_bp.logout') }}">Log out</a>
  {% endif %}

{% endblock %}

src/flask_app/flask_login_tutorial/templates/footer.jinja2
<section id="footer">
</section>

src/flask_app/flask_login_tutorial/templates/login.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
  <div class="form-wrapper">

    <div class="logo">
      <img src="{{ url_for('static', filename='dist/img/logo.png') }}" alt="logo"/>
    </div>

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Log In</h1>

    <form method="POST" action="/login">
      {{ form.csrf_token }}

      <fieldset class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='youremail@example.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

      <div class="login-signup">
        <span>Don't have an account? <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a></span>
      </div>

    </form>
  </div>
{% endblock %}

src/flask_app/flask_login_tutorial/templates/oauth.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}

  <h1>{{ body }}</h1>
  <div class="container-fluid">
  <div class="col-3"></div>
  <div class="container-fluid col-5">
  <h2 style="text-align: center; margin-right: 35vw;">Clients</h2>
  {% for client in clients %}
	<div class="container-fluid" style="margin: 0 auto; max-width: 46vw; text-align: left; background: #111; color: #ECECEC;"> 
		<pre>
		<strong>Client Info</strong>
		{%- for key in client.client_info %}
		<strong>{{ key }}: </strong>{{ client.client_info[key] }}
		{%- endfor %}
		<br>
		<strong>Client Metadata</strong>
		{%- for key in client.client_metadata %}
		<strong>{{ key }}: </strong>{{ client.client_metadata[key] }}
		{%- endfor %}
		</pre>
	</div>
	{% endfor %}
	</div>
	<div class="col-3"></div>
	</div>

  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('main_bp.logout') }}">Log out</a>
  {% endif %}

{% endblock %}

src/flask_app/flask_login_tutorial/templates/oauth2_authorize.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
  <h1>{{ body }}</h1>


<p>The application <strong>{{grant.client.client_name}}</strong> is requesting:
<strong>{{ grant.request.scope }}</strong>
</p>

<p>
  from You - a.k.a. <strong>{{ user.username }}</strong>
</p>

<form action="" method="post">
  <label>
    <input type="checkbox" name="confirm">
    <span>Consent?</span>
  </label>
  {% if not user %}
  <p>You haven't logged in. Log in with:</p>
  <div>
    <input type="text" name="username">
  </div>
  {% endif %}
  <br>
  <button>Submit</button>
</form>








  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('main_bp.logout') }}">Log out</a>
  {% endif %}

{% endblock %}

src/flask_app/flask_login_tutorial/templates/oauth2_create_client.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
  <h1>{{ body }}</h1>


<style>
  label, label > span { display: block; }
  label { margin: 15px 0; }
</style>

<a href="/oauth/">Home</a>

<form action="" method="post">
  <label>
    <span>Client Name</span>
    <input type="text" name="client_name">
  </label>
  <label>
    <span>Client URI</span>
    <input type="url" name="client_uri">
  </label>
  <label>
    <span>Allowed Scope</span>
    <input type="text" name="scope">
  </label>
  <label>
    <span>Redirect URIs</span>
    <textarea name="redirect_uri" cols="30" rows="10"></textarea>
  </label>
  <label>
    <span>Allowed Grant Types</span>
    <textarea name="grant_type" cols="30" rows="10"></textarea>
  </label>
  <label>
    <span>Allowed Response Types</span>
    <textarea name="response_type" cols="30" rows="10"></textarea>
  </label>
  <label>
    <span>Token Endpoint Auth Method</span>
    <select name="token_endpoint_auth_method">
      <option value="client_secret_basic">client_secret_basic</option>
      <option value="client_secret_post">client_secret_post</option>
      <option value="none">none</option>
    </select>
  </label>
  <button>Submit</button>
</form>


  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('main_bp.logout') }}">Log out</a>
  {% endif %}

{% endblock %}

src/flask_app/flask_login_tutorial/templates/scrape.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
  <h1>{{ body }}</h1>


<form action)="" method="POST">
<input style="min-width: 60vw;" type="text" name="url">
<input type="submit">
<br>
</form>
<textarea style='min-width: 80vw; min-height: 65vh;'>{{ scrape_json }}</textarea>


  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('main_bp.logout') }}">Log out</a>
  {% endif %}

{% endblock %}